package com.example.model;

public enum UserState {
    AWAITING_USERNAME,
    AWAITING_PASSWORD,
    AWAITING_EMAIL,
    AWAITING_PHONE,
    AWAITING_ID,
    AWAITING_LOGIN_USERNAME,
    AWAITING_LOGIN_PASSWORD,
    AWAITING_APPOINTMENT  // ✅ Add this line
, COMPLETED
}

